# Get all artists
// @no-cookie-jar
GET http://localhost:9080/eventViewer/api/artists
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu
###

# Get single artist

GET http://localhost:9080/eventViewer/api/artists/396457c5-3f20-49f1-8a7c-755a8d2f0b14

###

# Get single artist. Not existing.

GET http://localhost:9080/eventViewer/api/artists/396457c5-3f20-49f1-8a7c-755a8d2f0b15

###

# Put artist

PUT http://localhost:9080/eventViewer/api/artists/396457c5-3f20-49f1-8a7c-755a8d2f0b14
Content-Type: application/json

{
  "firstName": "Fryderyk",
  "lastName": "Szopen"
}

###

# Patch artist

PATCH http://localhost:9080/eventViewer/api/artists/396457c5-3f20-49f1-8a7c-755a8d2f0b14
Content-Type: application/json

{
  "firstName": "Fryderyk",
  "lastName": "Chopin"
}

###

# Delete artist

DELETE http://localhost:9080/eventViewer/api/artists/396457c5-3f20-49f1-8a7c-755a8d2f0b10

###

# Get single artist avatar

GET http://localhost:9080/eventViewer/api/artists/396457c5-3f20-49f1-8a7c-755a8d2f0b10/avatar

###

# Create artist avatar.

PUT http://localhost:9080/eventViewer/api/artists/396457c5-3f20-49f1-8a7c-755a8d2f0b10/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="crag-hack.png"

< src/main/resources/stenka/marcin/eventViewer/configuration/avatar/crag-hack.png
--boundary--

###

# Delete artist avatar

DELETE http://localhost:9080/eventViewer/api/artists/396457c5-3f20-49f1-8a7c-755a8d2f0b10/avatar

###

# Update artist avatar.

PATCH http://localhost:9080/eventViewer/api/artists/396457c5-3f20-49f1-8a7c-755a8d2f0b11/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="solmyr.png"

< src/main/resources/stenka/marcin/eventViewer/configuration/avatar/solmyr.png
--boundary--

###

# Get all locations

GET  http://localhost:9080/eventViewer/api/locations/
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

###

# Get single location

GET http://localhost:9080/eventViewer/api/locations/396457c5-3f20-49f1-8a7c-755a8d2f0b30

###

# Get location performances

GET http://localhost:9080/eventViewer/api/locations/396457c5-3f20-49f1-8a7c-755a8d2f0b30/performances

###

# Put location

PUT http://localhost:9080/eventViewer/api/locations/396457c5-3f20-49f1-8a7c-755a8d2f0b32
Content-Type: application/json

{
  "streetAddress": "Sopot",
  "maximumAudienceCapacity": "123",
  "LocationType": "FIELD"
}
###

# Patch location

PATCH http://localhost:9080/eventViewer/api/locations/396457c5-3f20-49f1-8a7c-755a8d2f0b32
Content-Type: application/json

{
  "streetAddress": "Sopot",
  "maximumAudienceCapacity": "10000",
  "LocationType": "FIELD"
}
###

# Delete location

DELETE http://localhost:9080/eventViewer/api/locations/396457c5-3f20-49f1-8a7c-755a8d2f0b30

###

# Get all performances

GET http://localhost:9080/eventViewer/api/performances

###

# Get single performance

GET http://localhost:9080/eventViewer/api/locations/396457c5-3f20-49f1-8a7c-755a8d2f0b30/performances/396457c5-3f20-49f1-8a7c-755a8d2f0b24

###

# Get artist performances

GET http://localhost:9080/eventViewer/api/artists/396457c5-3f20-49f1-8a7c-755a8d2f0b11/performances/

###

# Put performance

PUT http://localhost:9080/eventViewer/api/locations/396457c5-3f20-49f1-8a7c-755a8d2f0b30/performances/396457c5-3f20-49f1-8a7c-755a8d2f0b24
Content-Type: application/json

{
  "performanceType": "CONCERT",
  "date": "2222-01-22",
  "artist": "396457c5-3f20-49f1-8a7c-755a8d2f0b10"
}

###

# Patch performance

PATCH http://localhost:9080/eventViewer/api/locations/396457c5-3f20-49f1-8a7c-755a8d2f0b30/performances/396457c5-3f20-49f1-8a7c-755a8d2f0b24
Content-Type: application/json

{
  "performanceType": "CONCERT",
  "date": "2000-01-22"
}


###

# Delete performance
// @no-cookie-jar
DELETE http://localhost:9080/eventViewer/api/locations/396457c5-3f20-49f1-8a7c-755a8d2f0b30/performances/396457c5-3f20-49f1-8a7c-755a8d2f0b24

###

admin-service: YWRtaW4tc2VydmljZTphZG1pbmFkbWlu
Grabowski z USER, ADMIN: TWFyY2luOk1hcmNpbg==
Oskar z USER: T3NrYXI6T3NrYXI=